-- FORM Store — database schema
-- Postgres / Supabase
--
-- Run this first, then functions.sql, then seed.sql.
-- Objects are declared in dependency order: products -> variants -> orders
-- -> order_items -> stripe_events -> vton_usage -> views.

-- ---------------------------------------------------------------------------
-- products
--
-- One row per garment. Variants (size/colour) live in a separate table, so a
-- product is the thing a shopper browses and a variant is the thing that can
-- actually be sold.
--
-- rich_description is written for the RAG assistant, not for the product page:
-- fabric, cut, occasion, what it pairs with. It is the text that gets embedded.
-- vton_enabled gates the try-on button — not every product has a clean
-- garment shot suitable for the try-on API.
-- ---------------------------------------------------------------------------
CREATE TABLE public.products (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamptz NOT NULL DEFAULT now(),
  name              text,
  description       text,
  image_url         text,
  gender            text,
  price             numeric,
  rich_description  text,
  category          text,
  tryon_image_url   text,
  vton_enabled      boolean NOT NULL DEFAULT false
);

-- ---------------------------------------------------------------------------
-- variants
--
-- A sellable combination of size and colour. Stock lives here, never on the
-- product.
--
-- The CHECK on stock_quantity is a backstop: create_order already refuses to
-- decrement below zero, but if that logic is ever changed the database still
-- refuses to store a negative quantity.
-- ---------------------------------------------------------------------------
CREATE TABLE public.variants (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id      bigint REFERENCES public.products(id),
  created_at      timestamptz NOT NULL DEFAULT now(),
  size            text,
  color           text,
  stock_quantity  integer NOT NULL DEFAULT 0,
  CONSTRAINT variants_stock_quantity_check CHECK (stock_quantity >= 0)
);

-- ---------------------------------------------------------------------------
-- orders
--
-- Lifecycle: pending -> paid -> accepted -> shipped
--            pending -> expired | payment_failed
--
-- Validation lives here rather than only in the browser, because the frontend
-- can be bypassed by posting straight to the webhook. Phone and postcode
-- formats are per country, so a Greek address cannot be saved with a Polish
-- postcode.
--
-- id is GENERATED ALWAYS: order ids are never supplied by the caller.
-- ---------------------------------------------------------------------------
CREATE TABLE public.orders (
  id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created_at         timestamptz NOT NULL DEFAULT now(),
  customer_name      text NOT NULL,
  customer_email     text NOT NULL,
  total_amount       numeric NOT NULL,
  status             text NOT NULL DEFAULT 'pending',
  customer_phone     text NOT NULL,
  address_line1      text NOT NULL,
  address_line2      text,
  city               text NOT NULL,
  postcode           text NOT NULL,
  country            text NOT NULL DEFAULT 'GR',
  stripe_session_id  text,
  paid_at            timestamptz,

  CONSTRAINT orders_status_allowed CHECK (
    status = ANY (ARRAY['pending', 'paid', 'expired', 'payment_failed', 'accepted', 'shipped'])
  ),

  CONSTRAINT orders_country_allowed CHECK (
    country = ANY (ARRAY['GR', 'UA', 'CY', 'DE', 'PL'])
  ),

  CONSTRAINT orders_phone_format CHECK (
    CASE country
      WHEN 'GR' THEN customer_phone ~ '^\+30[26][0-9]{9}$'
      WHEN 'UA' THEN customer_phone ~ '^\+380[0-9]{9}$'
      WHEN 'CY' THEN customer_phone ~ '^\+357[0-9]{8}$'
      WHEN 'DE' THEN customer_phone ~ '^\+49[0-9]{6,11}$'
      WHEN 'PL' THEN customer_phone ~ '^\+48[0-9]{9}$'
      ELSE NULL::boolean
    END
  ),

  CONSTRAINT orders_postcode_format CHECK (
    CASE country
      WHEN 'GR' THEN postcode ~ '^[0-9]{5}$'
      WHEN 'UA' THEN postcode ~ '^[0-9]{5}$'
      WHEN 'CY' THEN postcode ~ '^[0-9]{4}$'
      WHEN 'DE' THEN postcode ~ '^[0-9]{5}$'
      WHEN 'PL' THEN postcode ~ '^[0-9]{2}-?[0-9]{3}$'
      ELSE NULL::boolean
    END
  )
);

-- A partial unique index, not a plain UNIQUE constraint.
-- One Stripe Checkout session can belong to at most one order, but orders that
-- never reached checkout have no session id at all — and many NULLs would
-- collide under a naive unique constraint in some engines. The WHERE clause
-- also keeps the index small: only orders that actually went to payment.
CREATE UNIQUE INDEX orders_stripe_session_id_key
  ON public.orders USING btree (stripe_session_id)
  WHERE stripe_session_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- order_items
--
-- price_at_purchase is copied from the product at checkout time on purpose.
-- Prices change; an order is a historical record and must not silently
-- re-price itself when the catalogue is edited.
--
-- ON DELETE CASCADE: deleting an order removes its lines. The variant FK has
-- no cascade — a variant that has been sold cannot simply be deleted.
-- ---------------------------------------------------------------------------
CREATE TABLE public.order_items (
  id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_id           bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  variant_id         bigint NOT NULL REFERENCES public.variants(id),
  quantity           integer NOT NULL,
  price_at_purchase  numeric NOT NULL
);

-- ---------------------------------------------------------------------------
-- stripe_events
--
-- Webhook idempotency, enforced by the database rather than by application
-- code. Stripe retries delivery until it gets a 2xx, so the same event id can
-- arrive several times. The primary key on event_id means the second insert
-- fails outright — there is no window in which two handlers both decide the
-- event is new.
-- ---------------------------------------------------------------------------
CREATE TABLE public.stripe_events (
  event_id     text PRIMARY KEY,
  type         text NOT NULL,
  order_id     bigint REFERENCES public.orders(id),
  received_at  timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- vton_usage
--
-- One row per calendar day, holding the number of try-on generations started.
-- The primary key on day is what makes increment_vton_usage work: it relies on
-- ON CONFLICT (day) to turn read-check-write into a single atomic statement.
-- ---------------------------------------------------------------------------
CREATE TABLE public.vton_usage (
  day          date PRIMARY KEY,
  generations  integer NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Foreign key indexes
--
-- Postgres does not index foreign key columns automatically. At this catalogue
-- size (49 products, ~300 variants) sequential scans are cheaper than index
-- lookups, so these are left commented out. They are the first thing to enable
-- if the dataset grows or if order history queries start to show up slow.
--
-- CREATE INDEX ON public.order_items (order_id);
-- CREATE INDEX ON public.order_items (variant_id);
-- CREATE INDEX ON public.variants (product_id);
-- CREATE INDEX ON public.stripe_events (order_id);
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- order_line_items (view)
--
-- Flattens an order into human-readable lines. Used by the admin notification
-- so the Telegram message can name the product, size and colour without the
-- workflow having to join three tables itself.
-- ---------------------------------------------------------------------------
CREATE VIEW public.order_line_items AS
SELECT
  oi.order_id,
  oi.quantity,
  oi.price_at_purchase,
  p.name AS product_name,
  v.size,
  v.color
FROM order_items oi
JOIN variants v ON v.id = oi.variant_id
JOIN products p ON p.id = v.product_id;

-- ---------------------------------------------------------------------------
-- product_embeddings (view)
--
-- Assembles the text that gets embedded into Qdrant, in the database rather
-- than in the workflow. Keeping it here means the embedding text is defined in
-- one place and can be inspected with a plain SELECT before re-indexing.
--
-- Colours are aggregated so a shopper asking for "something in navy" can match
-- a product whose description never mentions the colour.
-- ---------------------------------------------------------------------------
CREATE VIEW public.product_embeddings AS
SELECT
  p.id,
  p.name || '\n' || p.gender || '\n' || 'Colors: '
    || COALESCE(string_agg(DISTINCT v.color, ', '), 'n/a')
    || '\n' || p.rich_description AS embedding_text,
  p.gender
FROM products p
LEFT JOIN variants v ON v.product_id = p.id
GROUP BY p.id, p.name, p.gender, p.rich_description;
